### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by just-mikolaj** [Ombarus/clashAI#1]
`train_unit_ML (c:\Users\Admin\Desktop\clashAI-master\clashAI.py:1064)
run_all (c:\Users\Admin\Desktop\clashAI-master\clashAI.py:1094)
<module> (c:\Users\Admin\Desktop\clashAI-master\clashAI.py:1267)`

I have that problem

FileNotFoundError: [Errno 2] No such file or directory: 'data\\training_unit_list.json'

**Comment by Ombarus** [comment]
At the bottom of the documentation : "If some files are missing it is because they do not belong to me and I will not make them available, you will need to find them yourself."

train_unit_ML() was an attempt at using scipy to recognize units on the board. It never really worked but the missing files are part of the data I was using that was extracted from the APK and I will not share this since it does not belong to me.
